// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250615075433_Add_HomeNumberShadowHash_To_User")]
    partial class Add_HomeNumberShadowHash_To_User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Application.Common.OutboxMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccuredOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("occured_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_outbox_messages");

                    b.ToTable("outbox_messages");
                });

            modelBuilder.Entity("Domain.Aggregates.Package", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Dimensions")
                        .HasColumnType("TEXT")
                        .HasColumnName("dimensions");

                    b.Property<bool>("HouseDelivery")
                        .HasColumnType("INTEGER")
                        .HasColumnName("house_delivery");

                    b.Property<string>("InvoiceFileKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_file_key");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_paid");

                    b.Property<bool>("IsProhibited")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_prohibited");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("item_count");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_id");

                    b.Property<string>("PictureFileKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("picture_file_key");

                    b.Property<string>("PricePerKg")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_per_kg");

                    b.Property<string>("RaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("race_id");

                    b.Property<string>("RetailPrice")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("retail_price");

                    b.Property<string>("SenderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("sender_id");

                    b.Property<string>("WebsiteAddress")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("website_address");

                    b.Property<long?>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.ComplexProperty<Dictionary<string, object>>("TrackingCode", "Domain.Aggregates.Package.TrackingCode#TrackingCode", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("tracking_code");
                        });

                    b.HasKey("Id")
                        .HasName("p_k_package");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("i_x_package_owner_id");

                    b.HasIndex("RaceId")
                        .HasDatabaseName("i_x_package_race_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("i_x_package_sender_id");

                    b.ToTable("package");
                });

            modelBuilder.Entity("Domain.Aggregates.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AddressInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address_info")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true);

                    b.Property<string>("Balance")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("balance");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<string>("CultureInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("culture_info");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("email")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsQueryable", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsUniqueIndex", true);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("EmailShadowHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email_shadow_hash");

                    b.Property<string>("HomeNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("home_number")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsQueryable", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsUniqueIndex", true);

                    b.Property<string>("HomeNumberShadowHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("home_number_shadow_hash");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("lockout_end");

                    b.Property<bool>("NotifyBySms")
                        .HasColumnType("INTEGER")
                        .HasColumnName("notify_by_sms");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PersonalId")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_id")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsQueryable", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsUniqueIndex", true);

                    b.Property<string>("PersonalIdShadowHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("personal_id_shadow_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsQueryable", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsUniqueIndex", true);

                    b.Property<string>("PhoneNumberShadowHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone_number_shadow_hash");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("role");

                    b.Property<int>("RoomCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("room_code");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("TEXT")
                        .HasColumnName("security_stamp");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time_zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsQueryable", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsUniqueIndex", false);

                    b.Property<string>("UsernameShadowHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username_shadow_hash");

                    b.HasKey("Id")
                        .HasName("p_k_user");

                    b.HasIndex("PersonalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_personal_id");

                    b.HasIndex("RoomCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_user_room_code");

                    b.ToTable("user");
                });

            modelBuilder.Entity("Domain.Entities.PackageReceptionStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("package_id");

                    b.Property<string>("StaffId")
                        .HasColumnType("TEXT")
                        .HasColumnName("staff_id");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_package_reception_status");

                    b.HasIndex("PackageId")
                        .HasDatabaseName("i_x_package_reception_status_package_id");

                    b.HasIndex("StaffId")
                        .HasDatabaseName("i_x_package_reception_status_staff_id");

                    b.ToTable("package_reception_status");
                });

            modelBuilder.Entity("Domain.Entities.Race", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("TEXT")
                        .HasColumnName("arrival");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("destination");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT")
                        .HasColumnName("start");

                    b.HasKey("Id")
                        .HasName("p_k_race");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_race_name");

                    b.ToTable("race");
                });

            modelBuilder.Entity("Domain.Entities.UserLogin", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_by");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true);

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_active");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("location")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true);

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent")
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsEncrypted", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsQueryable", true)
                        .HasAnnotation("Klean.EntityFrameworkCore.DataProtection.IsUniqueIndex", false);

                    b.Property<string>("UserAgentShadowHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_agent_shadow_hash");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_x_user_login_user_id");

                    b.ToTable("user_login");
                });

            modelBuilder.Entity("Domain.Aggregates.Package", b =>
                {
                    b.HasOne("Domain.Aggregates.User", "Owner")
                        .WithMany("ReceivedPackages")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_package__user_owner_id");

                    b.HasOne("Domain.Entities.Race", "Race")
                        .WithMany("Packages")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_package__race_race_id");

                    b.HasOne("Domain.Aggregates.User", "Sender")
                        .WithMany("SentPackages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_package__user_sender_id");

                    b.Navigation("Owner");

                    b.Navigation("Race");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Domain.Entities.PackageReceptionStatus", b =>
                {
                    b.HasOne("Domain.Aggregates.Package", null)
                        .WithMany("Statuses")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_package_reception_status_package_package_id");

                    b.HasOne("Domain.Aggregates.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("f_k_package_reception_status_user_staff_id");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Domain.Entities.UserLogin", b =>
                {
                    b.HasOne("Domain.Aggregates.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_login_user_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Aggregates.Package", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("Domain.Aggregates.User", b =>
                {
                    b.Navigation("Logins");

                    b.Navigation("ReceivedPackages");

                    b.Navigation("SentPackages");
                });

            modelBuilder.Entity("Domain.Entities.Race", b =>
                {
                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
