using System.ComponentModel.DataAnnotations;

namespace Domain.ValueObjects;

public enum Category
{
    [Display(Name = "Other consumer products")] OtherConsumerProducts = 1,
    [Display(Name = "Auto Parts")] AutoParts,
    [Display(Name = "Audio equipment")] AudioEquipment,
    [Display(Name = "Audio equipment parts")] AudioEquipmentParts,
    [Display(Name = "Jewellery")] Jewellery,
    [Display(Name = "Key")] Key,
    [Display(Name = "Knife")] Knife,
    [Display(Name = "Video equipment")] VideoEquipment,
    [Display(Name = "Video equipment parts")] VideoEquipmentParts,
    [Display(Name = "Linen")] Linen,
    [Display(Name = "Self-adhesive tape")] SelfAdhesiveTape,
    [Display(Name = "Computer")] Computer,
    [Display(Name = "Computer parts")] ComputerParts,
    [Display(Name = "Cosmetics")] Cosmetics,
    [Display(Name = "Medicine")] Medicine,
    [Display(Name = "Glass products")] GlassProducts,
    [Display(Name = "Motorcycle parts")] MotorcycleParts,
    [Display(Name = "Music instruments")] MusicInstruments,
    [Display(Name = "Music instrument parts")] MusicInstrumentParts,
    [Display(Name = "Plants")] Plants,
    [Display(Name = "Printing products")] PrintingProducts,
    [Display(Name = "Perfumery")] Perfumery,
    [Display(Name = "Plastic stationery")] PlasticStationery,
    [Display(Name = "Plastic dining kitchen utensils")] PlasticDiningKitchenUtensils,
    [Display(Name = "Rubber products")] RubberProducts,
    [Display(Name = "Watch")] Watch,
    [Display(Name = "Measuring instruments")] MeasuringInstruments,
    [Display(Name = "Toy")] Toy,
    [Display(Name = "Glasses eyewear")] GlassesEyewear,
    [Display(Name = "Lock")] Lock,
    [Display(Name = "Supplements")] Supplements,
    [Display(Name = "Lighting equipments")] LightingEquipments,
    [Display(Name = "Office inventory")] OfficeInventory,
    [Display(Name = "Detergents and cleaning products")] DetergentsAndCleaningProducts,
    [Display(Name = "Scale")] Scale,
    [Display(Name = "Household furniture")] HouseholdFurniture,
    [Display(Name = "Home appliances")] HomeAppliances,
    [Display(Name = "Sport Equipment")] SportEquipment,
    [Display(Name = "Clothing")] Clothing,
    [Display(Name = "Phone")] Phone,
    [Display(Name = "Tent")] Tent,
    [Display(Name = "Porcelain Tableware")] PorcelainTableware,
    [Display(Name = "Footwear")] Footwear,
    [Display(Name = "Photo equipment")] PhotoEquipment,
    [Display(Name = "Photo equipment parts")] PhotoEquipmentParts,
    [Display(Name = "Network equipment")] NetworkEquipment,
    [Display(Name = "Bags")] Bags,
    [Display(Name = "Tools")] Tools,
    [Display(Name = "Different electronic and consumer products")] DifferentElectronicAndConsumerProducts,
}