using System.ComponentModel.DataAnnotations;

namespace Domain.ValueObjects;

public enum Category
{
    [Display(Name = "Consumer Products")] OtherConsumerProducts = 1,
    [Display(Name = "Auto Parts")] AutoParts,
    [Display(Name = "Audio Equip")] AudioEquipment,
    [Display(Name = "Audio Parts")] AudioEquipmentParts,
    [Display(Name = "Jewellery")] Jewellery,
    [Display(Name = "Key")] Key,
    [Display(Name = "Knife")] Knife,
    [Display(Name = "Video Equip")] VideoEquipment,
    [Display(Name = "Video Parts")] VideoEquipmentParts,
    [Display(Name = "Linen")] Linen,
    [Display(Name = "Adhesive Tape")] SelfAdhesiveTape,
    [Display(Name = "Computer")] Computer,
    [Display(Name = "Computer Parts")] ComputerParts,
    [Display(Name = "Cosmetics")] Cosmetics,
    [Display(Name = "Medicine")] Medicine,
    [Display(Name = "Glass Products")] GlassProducts,
    [Display(Name = "Motorcycle Parts")] MotorcycleParts,
    [Display(Name = "Music Instruments")] MusicInstruments,
    [Display(Name = "Music Parts")] MusicInstrumentParts,
    [Display(Name = "Plants")] Plants,
    [Display(Name = "Printing")] PrintingProducts,
    [Display(Name = "Perfumery")] Perfumery,
    [Display(Name = "Plastic Items")] PlasticStationery,
    [Display(Name = "Kitchen Utensils")] PlasticDiningKitchenUtensils,
    [Display(Name = "Rubber Products")] RubberProducts,
    [Display(Name = "Watch")] Watch,
    [Display(Name = "Measuring Tools")] MeasuringInstruments,
    [Display(Name = "Toy")] Toy,
    [Display(Name = "Eyewear")] GlassesEyewear,
    [Display(Name = "Lock")] Lock,
    [Display(Name = "Supplements")] Supplements,
    [Display(Name = "Lighting")] LightingEquipments,
    [Display(Name = "Office Items")] OfficeInventory,
    [Display(Name = "Cleaning Products")] DetergentsAndCleaningProducts,
    [Display(Name = "Scale")] Scale,
    [Display(Name = "Furniture")] HouseholdFurniture,
    [Display(Name = "Appliances")] HomeAppliances,
    [Display(Name = "Sport Gear")] SportEquipment,
    [Display(Name = "Clothing")] Clothing,
    [Display(Name = "Phone")] Phone,
    [Display(Name = "Tent")] Tent,
    [Display(Name = "Tableware")] PorcelainTableware,
    [Display(Name = "Footwear")] Footwear,
    [Display(Name = "Photo Equip")] PhotoEquipment,
    [Display(Name = "Photo Parts")] PhotoEquipmentParts,
    [Display(Name = "Network Equip")] NetworkEquipment,
    [Display(Name = "Bags")] Bags,
    [Display(Name = "Tools")] Tools,
    [Display(Name = "Electronics")] DifferentElectronicAndConsumerProducts,
}