//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Emails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Emails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Resources.Emails", typeof(Emails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a full list of prohibited items please see.
        /// </summary>
        internal static string for_a_full_list_of_prohibited_items_please_see {
            get {
                return ResourceManager.GetString("for_a_full_list_of_prohibited_items_please_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has arrived.
        /// </summary>
        internal static string has_arrived {
            get {
                return ResourceManager.GetString("has_arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has arrived at our warehouse.
        /// </summary>
        internal static string has_arrived_at_our_warehouse {
            get {
                return ResourceManager.GetString("has_arrived_at_our_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been delivered.
        /// </summary>
        internal static string has_been_delivered {
            get {
                return ResourceManager.GetString("has_been_delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been sent.
        /// </summary>
        internal static string has_been_sent {
            get {
                return ResourceManager.GetString("has_been_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this was not you please change your password immediately.
        /// </summary>
        internal static string if_this_was_not_you_please_change_your_password_immediately {
            get {
                return ResourceManager.GetString("if_this_was_not_you_please_change_your_password_immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this was you you can disregard this message.
        /// </summary>
        internal static string if_this_was_you_you_can_disregard_this_message {
            get {
                return ResourceManager.GetString("if_this_was_you_you_can_disregard_this_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not attempt to login to your account just now please change your password immediately.
        /// </summary>
        internal static string if_you_did_not_attempt_to_login_to_your_account_just_now_please_change_your_password_immediately {
            get {
                return ResourceManager.GetString("if_you_did_not_attempt_to_login_to_your_account_just_now_please_change_your_passw" +
                        "ord_immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request a password reset please contact our support immediately.
        /// </summary>
        internal static string if_you_did_not_request_a_password_reset_please_contact_our_support_immediately {
            get {
                return ResourceManager.GetString("if_you_did_not_request_a_password_reset_please_contact_our_support_immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request a password reset please ignore this email.
        /// </summary>
        internal static string if_you_did_not_request_a_password_reset_please_ignore_this_email {
            get {
                return ResourceManager.GetString("if_you_did_not_request_a_password_reset_please_ignore_this_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request this action please contact our support immediately.
        /// </summary>
        internal static string if_you_did_not_request_this_action_please_contact_our_support_immediately {
            get {
                return ResourceManager.GetString("if_you_did_not_request_this_action_please_contact_our_support_immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you think this if a mistake please contact our support team immediately.
        /// </summary>
        internal static string if_you_think_this_if_a_mistake_please_contact_our_support_team_immediately {
            get {
                return ResourceManager.GetString("if_you_think_this_if_a_mistake_please_contact_our_support_team_immediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is awaiting arrival in our warehouse.
        /// </summary>
        internal static string is_awaiting_arrival_in_our_warehouse {
            get {
                return ResourceManager.GetString("is_awaiting_arrival_in_our_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is recommended to change your password.
        /// </summary>
        internal static string it_is_recommended_to_change_your_password {
            get {
                return ResourceManager.GetString("it_is_recommended_to_change_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        internal static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package id.
        /// </summary>
        internal static string package_id {
            get {
                return ResourceManager.GetString("package_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the link below to reset your password.
        /// </summary>
        internal static string please_click_on_the_link_below_to_reset_your_password {
            get {
                return ResourceManager.GetString("please_click_on_the_link_below_to_reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use this email and password to login.
        /// </summary>
        internal static string please_use_this_email_and_password_to_login {
            get {
                return ResourceManager.GetString("please_use_this_email_and_password_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        internal static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone is trying to access your account do not delay resetting your password.
        /// </summary>
        internal static string someone_is_trying_to_access_your_account_do_not_delay_resetting_your_password {
            get {
                return ResourceManager.GetString("someone_is_trying_to_access_your_account_do_not_delay_resetting_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone just signed into your account.
        /// </summary>
        internal static string someone_just_signed_into_your_account {
            get {
                return ResourceManager.GetString("someone_just_signed_into_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support email.
        /// </summary>
        internal static string support_email {
            get {
                return ResourceManager.GetString("support_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email was sent to.
        /// </summary>
        internal static string this_email_was_sent_to {
            get {
                return ResourceManager.GetString("this_email_was_sent_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To recover your account just login with your email and password normally.
        /// </summary>
        internal static string to_recover_your_account_just_login_with_your_email_and_password_normally {
            get {
                return ResourceManager.GetString("to_recover_your_account_just_login_with_your_email_and_password_normally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tos.
        /// </summary>
        internal static string tos {
            get {
                return ResourceManager.GetString("tos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking code.
        /// </summary>
        internal static string tracking_code {
            get {
                return ResourceManager.GetString("tracking_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgent attention required.
        /// </summary>
        internal static string urgent_attention_required {
            get {
                return ResourceManager.GetString("urgent_attention_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are excited to have you on board.
        /// </summary>
        internal static string we_are_excited_to_have_you_on_board {
            get {
                return ResourceManager.GetString("we_are_excited_to_have_you_on_board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry to see you go however you have a 30 day grace period to recover your account.
        /// </summary>
        internal static string we_are_sorry_to_see_you_go_however_you_have_a_30_day_grace_period_to_recover_your_account {
            get {
                return ResourceManager.GetString("we_are_sorry_to_see_you_go_however_you_have_a_30_day_grace_period_to_recover_your" +
                        "_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to sangoway.
        /// </summary>
        internal static string welcome_to_sangoway {
            get {
                return ResourceManager.GetString("welcome_to_sangoway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You requested a password reset for your account.
        /// </summary>
        internal static string you_requested_a_password_reset_for_your_account {
            get {
                return ResourceManager.GetString("you_requested_a_password_reset_for_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully verified your email account.
        /// </summary>
        internal static string you_successfully_verified_your_email_account {
            get {
                return ResourceManager.GetString("you_successfully_verified_your_email_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created by an administrator.
        /// </summary>
        internal static string your_account_has_been_created_by_an_administrator {
            get {
                return ResourceManager.GetString("your_account_has_been_created_by_an_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is scheduled for deletion.
        /// </summary>
        internal static string your_account_is_scheduled_for_deletion {
            get {
                return ResourceManager.GetString("your_account_is_scheduled_for_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current balance is.
        /// </summary>
        internal static string your_current_balance_is {
            get {
                return ResourceManager.GetString("your_current_balance_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your package has been deemed to contain prohibited items by our staff.
        /// </summary>
        internal static string your_package_has_been_deemed_to_contain_prohibited_items_by_our_staff {
            get {
                return ResourceManager.GetString("your_package_has_been_deemed_to_contain_prohibited_items_by_our_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your package has status.
        /// </summary>
        internal static string your_package_has_status {
            get {
                return ResourceManager.GetString("your_package_has_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your package with the tracking code.
        /// </summary>
        internal static string your_package_with_the_tracking_code {
            get {
                return ResourceManager.GetString("your_package_with_the_tracking_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your packages shipping fee has been paid.
        /// </summary>
        internal static string your_packages_shipping_fee_has_been_paid {
            get {
                return ResourceManager.GetString("your_packages_shipping_fee_has_been_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been successfully changed.
        /// </summary>
        internal static string your_password_has_been_successfully_changed {
            get {
                return ResourceManager.GetString("your_password_has_been_successfully_changed", resourceCulture);
            }
        }
    }
}
