//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you&apos;ve ventured into the unknown digital realm..
        /// </summary>
        public static string _404_description {
            get {
                return ResourceManager.GetString("404_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - Lost in Cyberspace.
        /// </summary>
        public static string _404_header {
            get {
                return ResourceManager.GetString("404_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to home.
        /// </summary>
        public static string _404_return_home {
            get {
                return ResourceManager.GetString("404_return_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using.
        /// </summary>
        public static string _using {
            get {
                return ResourceManager.GetString("_using", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our achievements.
        /// </summary>
        public static string about_achievements {
            get {
                return ResourceManager.GetString("about_achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since our inception, we have successfully delivered 2,320 parcels from the USA to Georgia, helping countless customers enjoy affordable and reliable shipping..
        /// </summary>
        public static string about_achievements_description {
            get {
                return ResourceManager.GetString("about_achievements_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to our shipping service! We pride ourselves on being the most affordable and reliable delivery service for parcels from the USA to Georgia..
        /// </summary>
        public static string about_description {
            get {
                return ResourceManager.GetString("about_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorgi Sanakoevi.
        /// </summary>
        public static string about_giorgi_sanakoevi {
            get {
                return ResourceManager.GetString("about_giorgi_sanakoevi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string about_mission {
            get {
                return ResourceManager.GetString("about_mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goal is to make international shipping affordable and hassle-free. We ensure that your parcels are delivered safely and on time from the USA to Georgia..
        /// </summary>
        public static string about_mission_description {
            get {
                return ResourceManager.GetString("about_mission_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are we.
        /// </summary>
        public static string about_who_are_we {
            get {
                return ResourceManager.GetString("about_who_are_we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a small business driven by a passion for delivering value to our customers..
        /// </summary>
        public static string about_who_are_we_description {
            get {
                return ResourceManager.GetString("about_who_are_we_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why us?.
        /// </summary>
        public static string about_why_us {
            get {
                return ResourceManager.GetString("about_why_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We combine cost-effective pricing, personalized service, and a commitment to excellence to ensure that your shipping experience is second to none. When you choose us, you’re supporting a dedicated small business that values your trust..
        /// </summary>
        public static string about_why_us_description {
            get {
                return ResourceManager.GetString("about_why_us_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string account_delete_confirmation {
            get {
                return ResourceManager.GetString("account_delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add address.
        /// </summary>
        public static string add_address {
            get {
                return ResourceManager.GetString("add_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new payment method to your account.
        /// </summary>
        public static string add_new_payment_method_to_your_account {
            get {
                return ResourceManager.GetString("add_new_payment_method_to_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add online.
        /// </summary>
        public static string add_online {
            get {
                return ResourceManager.GetString("add_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add package to race.
        /// </summary>
        public static string add_package_to_race {
            get {
                return ResourceManager.GetString("add_package_to_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add personal.
        /// </summary>
        public static string add_personal {
            get {
                return ResourceManager.GetString("add_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add race.
        /// </summary>
        public static string add_race {
            get {
                return ResourceManager.GetString("add_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to race.
        /// </summary>
        public static string add_to_race {
            get {
                return ResourceManager.GetString("add_to_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add user.
        /// </summary>
        public static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2 room code.
        /// </summary>
        public static string address_2_room_code {
            get {
                return ResourceManager.GetString("address_2_room_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address updated successfully.
        /// </summary>
        public static string address_updated_successfully {
            get {
                return ResourceManager.GetString("address_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string addresses {
            get {
                return ResourceManager.GetString("addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin dashboard.
        /// </summary>
        public static string admin_dashboard {
            get {
                return ResourceManager.GetString("admin_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After this transaction you will have.
        /// </summary>
        public static string after_this_transaction_you_will_have {
            get {
                return ResourceManager.GetString("after_this_transaction_you_will_have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport name.
        /// </summary>
        public static string airport_name {
            get {
                return ResourceManager.GetString("airport_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All packages.
        /// </summary>
        public static string all_packages {
            get {
                return ResourceManager.GetString("all_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All races.
        /// </summary>
        public static string all_races {
            get {
                return ResourceManager.GetString("all_races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string all_rights_reserved {
            get {
                return ResourceManager.GetString("all_rights_reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string all_users {
            get {
                return ResourceManager.GetString("all_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string already_have_an_account {
            get {
                return ResourceManager.GetString("already_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calulator.
        /// </summary>
        public static string calculator {
            get {
                return ResourceManager.GetString("calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the required parameters of the parcel and the calculator will calculate the cost of the delivery.
        /// </summary>
        public static string calculator_description {
            get {
                return ResourceManager.GetString("calculator_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find out more about how we calculate the package prices please visit our.
        /// </summary>
        public static string calculator_price_notice {
            get {
                return ResourceManager.GetString("calculator_price_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To find out more about volumetric weight and how it&apos;s calculated please visit our.
        /// </summary>
        public static string calculator_volumetric_notice {
            get {
                return ResourceManager.GetString("calculator_volumetric_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA has errors.
        /// </summary>
        public static string captcha_errors {
            get {
                return ResourceManager.GetString("captcha_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA expired, please do it again.
        /// </summary>
        public static string captcha_expired_please_do_it_again {
            get {
                return ResourceManager.GetString("captcha_expired_please_do_it_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string change_your_password {
            get {
                return ResourceManager.GetString("change_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose receiver.
        /// </summary>
        public static string choose_receiver {
            get {
                return ResourceManager.GetString("choose_receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose sender.
        /// </summary>
        public static string choose_sender {
            get {
                return ResourceManager.GetString("choose_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string confirm_email {
            get {
                return ResourceManager.GetString("confirm_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string confirm_new_password {
            get {
                return ResourceManager.GetString("confirm_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact dev team.
        /// </summary>
        public static string contact_dev_team {
            get {
                return ResourceManager.GetString("contact_dev_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string create_an_account {
            get {
                return ResourceManager.GetString("create_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new user.
        /// </summary>
        public static string create_new_user {
            get {
                return ResourceManager.GetString("create_new_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create race.
        /// </summary>
        public static string create_race {
            get {
                return ResourceManager.GetString("create_race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create receiver.
        /// </summary>
        public static string create_receiver {
            get {
                return ResourceManager.GetString("create_receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create sender.
        /// </summary>
        public static string create_sender {
            get {
                return ResourceManager.GetString("create_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string created_at {
            get {
                return ResourceManager.GetString("created_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string current_password {
            get {
                return ResourceManager.GetString("current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare.
        /// </summary>
        public static string declare {
            get {
                return ResourceManager.GetString("declare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare new online package.
        /// </summary>
        public static string declare_new_online_package {
            get {
                return ResourceManager.GetString("declare_new_online_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declare new personal package.
        /// </summary>
        public static string declare_new_personal_package {
            get {
                return ResourceManager.GetString("declare_new_personal_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string delete_account {
            get {
                return ResourceManager.GetString("delete_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible. All your data will be lost. You will have a 30 day grace period to recover your account.&lt;br/&gt;
        ///        To recover your account, just login with your email and password..
        /// </summary>
        public static string delete_warning {
            get {
                return ResourceManager.GetString("delete_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string destination {
            get {
                return ResourceManager.GetString("destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected a networking issue.
        /// </summary>
        public static string detected_a_networking_issue {
            get {
                return ResourceManager.GetString("detected_a_networking_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string dev_team {
            get {
                return ResourceManager.GetString("dev_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive an email?.
        /// </summary>
        public static string didnt_receive_an_email {
            get {
                return ResourceManager.GetString("didnt_receive_an_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string dimensions {
            get {
                return ResourceManager.GetString("dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string dont_have_an_account {
            get {
                return ResourceManager.GetString("dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        public static string email_sent {
            get {
                return ResourceManager.GetString("email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the package tracking code and see if we have it in the system.
        /// </summary>
        public static string enter_the_package_tracking_code_and_see_if_we_have_it_in_the_system {
            get {
                return ResourceManager.GetString("enter_the_package_tracking_code_and_see_if_we_have_it_in_the_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the price per kilogram here.
        /// </summary>
        public static string enter_the_price_per_kilogram_here {
            get {
                return ResourceManager.GetString("enter_the_price_per_kilogram_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email, and we&apos;ll send you a link..
        /// </summary>
        public static string enter_your_email_and_well_send_you_a_new_link {
            get {
                return ResourceManager.GetString("enter_your_email_and_well_send_you_a_new_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to receive notifications about product updates and our newsletter..
        /// </summary>
        public static string enter_your_email_to_receive_notifications_about_product_updates {
            get {
                return ResourceManager.GetString("enter_your_email_to_receive_notifications_about_product_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate token.
        /// </summary>
        public static string failed_to_validate_token {
            get {
                return ResourceManager.GetString("failed_to_validate_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanGoWay is a platform that helps deliver packages from USA to Georgia..
        /// </summary>
        public static string faq_1_a {
            get {
                return ResourceManager.GetString("faq_1_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is SanGoWay?.
        /// </summary>
        public static string faq_1_q {
            get {
                return ResourceManager.GetString("faq_1_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanGoWay uses the weight and dimensions of your package to calculate the cost of shipping from the USA to Georgia..
        /// </summary>
        public static string faq_2_a {
            get {
                return ResourceManager.GetString("faq_2_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        public static string faq_2_q {
            get {
                return ResourceManager.GetString("faq_2_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started is easy. Just sign up and start using our services.
        /// </summary>
        public static string faq_3_a {
            get {
                return ResourceManager.GetString("faq_3_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I get started?.
        /// </summary>
        public static string faq_3_q {
            get {
                return ResourceManager.GetString("faq_3_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SanGoWay accepts payment via credit card and bank transfer..
        /// </summary>
        public static string faq_4_a {
            get {
                return ResourceManager.GetString("faq_4_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I pay for shipping?.
        /// </summary>
        public static string faq_4_q {
            get {
                return ResourceManager.GetString("faq_4_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your package is shipped, you will receive a tracking number that you can use to track your package..
        /// </summary>
        public static string faq_5_a {
            get {
                return ResourceManager.GetString("faq_5_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I track my package?.
        /// </summary>
        public static string faq_5_q {
            get {
                return ResourceManager.GetString("faq_5_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once your package arrives in Georgia, you can pick it up at our office or have it delivered to your address..
        /// </summary>
        public static string faq_6_a {
            get {
                return ResourceManager.GetString("faq_6_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do I get my package?.
        /// </summary>
        public static string faq_6_q {
            get {
                return ResourceManager.GetString("faq_6_q", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight code.
        /// </summary>
        public static string flight_code {
            get {
                return ResourceManager.GetString("flight_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From last month.
        /// </summary>
        public static string from_last_month {
            get {
                return ResourceManager.GetString("from_last_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA failed to load, please reload the page.
        /// </summary>
        public static string google_recaptcha_error_please_reload {
            get {
                return ResourceManager.GetString("google_recaptcha_error_please_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world.
        /// </summary>
        public static string hello_world {
            get {
                return ResourceManager.GetString("hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string hero_cta_text {
            get {
                return ResourceManager.GetString("hero_cta_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a new company in the shipping industry, offering reliable, fast, and affordable services worldwide..
        /// </summary>
        public static string hero_description {
            get {
                return ResourceManager.GetString("hero_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Company from USA to Georgia.
        /// </summary>
        public static string hero_title {
            get {
                return ResourceManager.GetString("hero_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House delivery.
        /// </summary>
        public static string house_delivery {
            get {
                return ResourceManager.GetString("house_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How it works.
        /// </summary>
        public static string how_it_works {
            get {
                return ResourceManager.GetString("how_it_works", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Register.
        /// </summary>
        public static string how_step_1 {
            get {
                return ResourceManager.GetString("how_step_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account to use our services!.
        /// </summary>
        public static string how_step_1_description {
            get {
                return ResourceManager.GetString("how_step_1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Copy your address.
        /// </summary>
        public static string how_step_2 {
            get {
                return ResourceManager.GetString("how_step_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you register, You will receive an address that you can use for online shopping.&lt;br/&gt;&lt;br/&gt;Copy the address and save it on your desired ECommerce website.
        /// </summary>
        public static string how_step_2_description {
            get {
                return ResourceManager.GetString("how_step_2_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3: Add packages.
        /// </summary>
        public static string how_step_3 {
            get {
                return ResourceManager.GetString("how_step_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you buy products online, Please declare them in your SanGoWay account..
        /// </summary>
        public static string how_step_3_description {
            get {
                return ResourceManager.GetString("how_step_3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4: Receive packages!.
        /// </summary>
        public static string how_step_4 {
            get {
                return ResourceManager.GetString("how_step_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After your package arrives, you will be able to pay for it.&lt;br/&gt;&lt;br/&gt;After you pay for shipping, you will receive your package.
        /// </summary>
        public static string how_step_4_description {
            get {
                return ResourceManager.GetString("how_step_4_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a confirmed account with us, a link with the password reset code will be sent to you..
        /// </summary>
        public static string if_you_have_an_account_with_us_you_should_receive_a_password_reset_code_shortly {
            get {
                return ResourceManager.GetString("if_you_have_an_account_with_us_you_should_receive_a_password_reset_code_shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string invalid_token {
            get {
                return ResourceManager.GetString("invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is paid.
        /// </summary>
        public static string is_paid {
            get {
                return ResourceManager.GetString("is_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item count.
        /// </summary>
        public static string item_count {
            get {
                return ResourceManager.GetString("item_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing.
        /// </summary>
        public static string landing {
            get {
                return ResourceManager.GetString("landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string last_update {
            get {
                return ResourceManager.GetString("last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string locked_out {
            get {
                return ResourceManager.GetString("locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login as this user.
        /// </summary>
        public static string login_as_this_user {
            get {
                return ResourceManager.GetString("login_as_this_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string login_to_your_account {
            get {
                return ResourceManager.GetString("login_to_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string manage_account {
            get {
                return ResourceManager.GetString("manage_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage notifications.
        /// </summary>
        public static string manage_notifications {
            get {
                return ResourceManager.GetString("manage_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your addresses.
        /// </summary>
        public static string manage_your_addresses {
            get {
                return ResourceManager.GetString("manage_your_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your personal info.
        /// </summary>
        public static string manage_your_personal_info {
            get {
                return ResourceManager.GetString("manage_your_personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as delivered.
        /// </summary>
        public static string mark_as_delivered {
            get {
                return ResourceManager.GetString("mark_as_delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark package as delivered to user.
        /// </summary>
        public static string mark_package_as_delivered_to_user {
            get {
                return ResourceManager.GetString("mark_package_as_delivered_to_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Addresses.
        /// </summary>
        public static string my_addresses {
            get {
                return ResourceManager.GetString("my_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Packages.
        /// </summary>
        public static string my_packages {
            get {
                return ResourceManager.GetString("my_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification preferences.
        /// </summary>
        public static string notification_preferences {
            get {
                return ResourceManager.GetString("notification_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string origin {
            get {
                return ResourceManager.GetString("origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        public static string owner {
            get {
                return ResourceManager.GetString("owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string package {
            get {
                return ResourceManager.GetString("package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package arrived at destination.
        /// </summary>
        public static string package_arrived_at_destination {
            get {
                return ResourceManager.GetString("package_arrived_at_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package contains prohibited items.
        /// </summary>
        public static string package_contains_prohibited_items {
            get {
                return ResourceManager.GetString("package_contains_prohibited_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package delivered to user.
        /// </summary>
        public static string package_delivered_to_user {
            get {
                return ResourceManager.GetString("package_delivered_to_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package description.
        /// </summary>
        public static string package_description {
            get {
                return ResourceManager.GetString("package_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package details.
        /// </summary>
        public static string package_details {
            get {
                return ResourceManager.GetString("package_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package id.
        /// </summary>
        public static string package_id {
            get {
                return ResourceManager.GetString("package_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages processed.
        /// </summary>
        public static string packages_processed {
            get {
                return ResourceManager.GetString("packages_processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner sites.
        /// </summary>
        public static string partner_sites {
            get {
                return ResourceManager.GetString("partner_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 12 characters.
        /// </summary>
        public static string password_must_contain_at_least_12_characters {
            get {
                return ResourceManager.GetString("password_must_contain_at_least_12_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully.
        /// </summary>
        public static string password_reset_successfully {
            get {
                return ResourceManager.GetString("password_reset_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay for shipping.
        /// </summary>
        public static string pay_for_shipping {
            get {
                return ResourceManager.GetString("pay_for_shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        public static string personal_id {
            get {
                return ResourceManager.GetString("personal_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string personal_info {
            get {
                return ResourceManager.GetString("personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string picture {
            get {
                return ResourceManager.GetString("picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email.
        /// </summary>
        public static string please_check_your_email {
            get {
                return ResourceManager.GetString("please_check_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and spam folders.
        /// </summary>
        public static string please_check_your_email_and_spam_folder {
            get {
                return ResourceManager.GetString("please_check_your_email_and_spam_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete CAPTCHA before continuing.
        /// </summary>
        public static string please_complete_captcha_before_continuing {
            get {
                return ResourceManager.GetString("please_complete_captcha_before_continuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please keep in mind, the weight will get rounded up to the nearest 100 grams..
        /// </summary>
        public static string please_keep_in_mind_the_weight_will_get_rounded_up_to_the_nearest_100_grams {
            get {
                return ResourceManager.GetString("please_keep_in_mind_the_weight_will_get_rounded_up_to_the_nearest_100_grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please predeclare your online shopping package so that there arent any delays when shipping id.
        /// </summary>
        public static string please_predeclare_your_online_shopping_package_so_that_there_arent_any_delays_when_shipping_id {
            get {
                return ResourceManager.GetString("please_predeclare_your_online_shopping_package_so_that_there_arent_any_delays_whe" +
                        "n_shipping_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per.
        /// </summary>
        public static string price_per {
            get {
                return ResourceManager.GetString("price_per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print label.
        /// </summary>
        public static string print_label {
            get {
                return ResourceManager.GetString("print_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string race {
            get {
                return ResourceManager.GetString("race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race details.
        /// </summary>
        public static string race_details {
            get {
                return ResourceManager.GetString("race_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race id.
        /// </summary>
        public static string race_id {
            get {
                return ResourceManager.GetString("race_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race name.
        /// </summary>
        public static string race_name {
            get {
                return ResourceManager.GetString("race_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string rate_per_kilo {
            get {
                return ResourceManager.GetString("rate_per_kilo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        public static string receive {
            get {
                return ResourceManager.GetString("receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive at destination.
        /// </summary>
        public static string receive_at_destination {
            get {
                return ResourceManager.GetString("receive_at_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive at warehouse.
        /// </summary>
        public static string receive_at_warehouse {
            get {
                return ResourceManager.GetString("receive_at_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive package at warehouse.
        /// </summary>
        public static string receive_package_at_warehouse {
            get {
                return ResourceManager.GetString("receive_package_at_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS notifications?.
        /// </summary>
        public static string receive_sms_notifications {
            get {
                return ResourceManager.GetString("receive_sms_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiver.
        /// </summary>
        public static string receiver {
            get {
                return ResourceManager.GetString("receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register confirmation.
        /// </summary>
        public static string register_confirmation {
            get {
                return ResourceManager.GetString("register_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string reload {
            get {
                return ResourceManager.GetString("reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string resend {
            get {
                return ResourceManager.GetString("resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string resend_email_confirmation {
            get {
                return ResourceManager.GetString("resend_email_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail price.
        /// </summary>
        public static string retail_price {
            get {
                return ResourceManager.GetString("retail_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return home.
        /// </summary>
        public static string return_home {
            get {
                return ResourceManager.GetString("return_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room code.
        /// </summary>
        public static string room_code {
            get {
                return ResourceManager.GetString("room_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string save_changes {
            get {
                return ResourceManager.GetString("save_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save preferences.
        /// </summary>
        public static string save_preferences {
            get {
                return ResourceManager.GetString("save_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select option.
        /// </summary>
        public static string select_option {
            get {
                return ResourceManager.GetString("select_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string sender {
            get {
                return ResourceManager.GetString("sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping price.
        /// </summary>
        public static string shipping_price {
            get {
                return ResourceManager.GetString("shipping_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping revenue.
        /// </summary>
        public static string shipping_revenue {
            get {
                return ResourceManager.GetString("shipping_revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff dashboard.
        /// </summary>
        public static string staff_dashboard {
            get {
                return ResourceManager.GetString("staff_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is unavailable in Georgia.
        /// </summary>
        public static string state_unavailable_for_georgia {
            get {
                return ResourceManager.GetString("state_unavailable_for_georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status updates.
        /// </summary>
        public static string status_updates {
            get {
                return ResourceManager.GetString("status_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        public static string street_address {
            get {
                return ResourceManager.GetString("street_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takeoff.
        /// </summary>
        public static string takeoff {
            get {
                return ResourceManager.GetString("takeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms.
        /// </summary>
        public static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;This platform has transformed how I work. Highly recommended!&quot;.
        /// </summary>
        public static string testimonial_1 {
            get {
                return ResourceManager.GetString("testimonial_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamar Bibileishvili.
        /// </summary>
        public static string testimonial_1_author {
            get {
                return ResourceManager.GetString("testimonial_1_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The best decision I made this year. Incredible support and features!&quot;.
        /// </summary>
        public static string testimonial_2 {
            get {
                return ResourceManager.GetString("testimonial_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ani Martiashvili.
        /// </summary>
        public static string testimonial_2_author {
            get {
                return ResourceManager.GetString("testimonial_2_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Outstanding quality and attention to detail. They truly care!&quot;.
        /// </summary>
        public static string testimonial_3 {
            get {
                return ResourceManager.GetString("testimonial_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mariam Nikoladze.
        /// </summary>
        public static string testimonial_3_author {
            get {
                return ResourceManager.GetString("testimonial_3_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;I can&apos;t imagine going back to how things were before this service.&quot;.
        /// </summary>
        public static string testimonial_4 {
            get {
                return ResourceManager.GetString("testimonial_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorgi Baqradze.
        /// </summary>
        public static string testimonial_4_author {
            get {
                return ResourceManager.GetString("testimonial_4_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What our customers are saying.
        /// </summary>
        public static string testimonial_header {
            get {
                return ResourceManager.GetString("testimonial_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using our services.
        /// </summary>
        public static string thank_you_for_using_our_services {
            get {
                return ResourceManager.GetString("thank_you_for_using_our_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token you provided is invalid.
        /// </summary>
        public static string the_token_you_provided_is_invalid {
            get {
                return ResourceManager.GetString("the_token_you_provided_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again in 5 minutes.
        /// </summary>
        public static string this_account_has_been_locked_out_please_try_again_later {
            get {
                return ResourceManager.GetString("this_account_has_been_locked_out_please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a major issue.
        /// </summary>
        public static string this_is_not_a_major_issue {
            get {
                return ResourceManager.GetString("this_is_not_a_major_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package contains prohibited items.
        /// </summary>
        public static string this_package_contains_prohibited_items {
            get {
                return ResourceManager.GetString("this_package_contains_prohibited_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This package has not been paid for cant deliver.
        /// </summary>
        public static string this_package_has_not_been_paid_for_cant_deliver {
            get {
                return ResourceManager.GetString("this_package_has_not_been_paid_for_cant_deliver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue using the website please reload.
        /// </summary>
        public static string to_continue_please_reload {
            get {
                return ResourceManager.GetString("to_continue_please_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To your account.
        /// </summary>
        public static string to_your_account {
            get {
                return ResourceManager.GetString("to_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle theme.
        /// </summary>
        public static string toggle_theme {
            get {
                return ResourceManager.GetString("toggle_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up.
        /// </summary>
        public static string top_up {
            get {
                return ResourceManager.GetString("top_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up balance.
        /// </summary>
        public static string top_up_balance {
            get {
                return ResourceManager.GetString("top_up_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount due.
        /// </summary>
        public static string total_amount_due {
            get {
                return ResourceManager.GetString("total_amount_due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string total_price {
            get {
                return ResourceManager.GetString("total_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track package.
        /// </summary>
        public static string track_package {
            get {
                return ResourceManager.GetString("track_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking code.
        /// </summary>
        public static string tracking_code {
            get {
                return ResourceManager.GetString("tracking_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;delete&apos; to confirm.
        /// </summary>
        public static string type_delete_to_confirm {
            get {
                return ResourceManager.GetString("type_delete_to_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update address.
        /// </summary>
        public static string update_address {
            get {
                return ResourceManager.GetString("update_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User dashboard.
        /// </summary>
        public static string user_dashboard {
            get {
                return ResourceManager.GetString("user_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        public static string user_details {
            get {
                return ResourceManager.GetString("user_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumetric price.
        /// </summary>
        public static string volumetric_price {
            get {
                return ResourceManager.GetString("volumetric_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website address.
        /// </summary>
        public static string website_address {
            get {
                return ResourceManager.GetString("website_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string welcome_back {
            get {
                return ResourceManager.GetString("welcome_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the best app ever!.
        /// </summary>
        public static string welcome_to_our_app {
            get {
                return ResourceManager.GetString("welcome_to_our_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you receive a package at the warehouse declare them here.
        /// </summary>
        public static string when_you_receive_a_package_at_the_warehouse_declare_them_here {
            get {
                return ResourceManager.GetString("when_you_receive_a_package_at_the_warehouse_declare_them_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced tracking.
        /// </summary>
        public static string why_advanced_tracking {
            get {
                return ResourceManager.GetString("why_advanced_tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our advanced tracking system and professional team guarantee peace of mind from the moment you send your parcel to the moment it reaches its destination..
        /// </summary>
        public static string why_advanced_tracking_description {
            get {
                return ResourceManager.GetString("why_advanced_tracking_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved packages.
        /// </summary>
        public static string why_cards_moving_items {
            get {
                return ResourceManager.GetString("why_cards_moving_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages from Georgia.
        /// </summary>
        public static string why_cards_packages_from_geo {
            get {
                return ResourceManager.GetString("why_cards_packages_from_geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages from USA.
        /// </summary>
        public static string why_cards_packages_from_usa {
            get {
                return ResourceManager.GetString("why_cards_packages_from_usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages stored.
        /// </summary>
        public static string why_cards_storage_items {
            get {
                return ResourceManager.GetString("why_cards_storage_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap prices!.
        /// </summary>
        public static string why_cheap_prices {
            get {
                return ResourceManager.GetString("why_cheap_prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide unmatched shipping solutions tailored to meet your unique needs, ensuring timely and secure deliveries every time..
        /// </summary>
        public static string why_cheap_prices_description {
            get {
                return ResourceManager.GetString("why_cheap_prices_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vast Experience.
        /// </summary>
        public static string why_experience {
            get {
                return ResourceManager.GetString("why_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With years of experience in the logistics industry, we are dedicated to delivering exceptional service, whether you are shipping packages across the country or around the globe..
        /// </summary>
        public static string why_experience_description {
            get {
                return ResourceManager.GetString("why_experience_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why SanGoWay?.
        /// </summary>
        public static string why_sangoway {
            get {
                return ResourceManager.GetString("why_sangoway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to pay x amount.
        /// </summary>
        public static string would_you_like_to_pay_x_amount {
            get {
                return ResourceManager.GetString("would_you_like_to_pay_x_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cancelled the payment.
        /// </summary>
        public static string you_cancelled_the_payment {
            get {
                return ResourceManager.GetString("you_cancelled_the_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource.
        /// </summary>
        public static string you_do_not_have_access_to_this_resource {
            get {
                return ResourceManager.GetString("you_do_not_have_access_to_this_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a 30 day grace period to recover your account. To recover your account, login with your email and password..
        /// </summary>
        public static string you_have_a_30_day_grace_period_to_recover_your_account_to_recover_simply_login {
            get {
                return ResourceManager.GetString("you_have_a_30_day_grace_period_to_recover_your_account_to_recover_simply_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to our.
        /// </summary>
        public static string you_must_agree_to_our {
            get {
                return ResourceManager.GetString("you_must_agree_to_our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully deposited.
        /// </summary>
        public static string you_successfully_deposited {
            get {
                return ResourceManager.GetString("you_successfully_deposited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully reset your password.
        /// </summary>
        public static string you_successfully_reset_your_password {
            get {
                return ResourceManager.GetString("you_successfully_reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been confirmed.
        /// </summary>
        public static string your_account_has_been_confirmed {
            get {
                return ResourceManager.GetString("your_account_has_been_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is scheduled for deletion.
        /// </summary>
        public static string your_account_is_scheduled_for_deletion {
            get {
                return ResourceManager.GetString("your_account_is_scheduled_for_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance.
        /// </summary>
        public static string your_balance {
            get {
                return ResourceManager.GetString("your_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your packages.
        /// </summary>
        public static string your_packages {
            get {
                return ResourceManager.GetString("your_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string your_password_has_been_reset {
            get {
                return ResourceManager.GetString("your_password_has_been_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment info is secure.
        /// </summary>
        public static string your_payment_info_is_secure {
            get {
                return ResourceManager.GetString("your_payment_info_is_secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal data is protected.
        /// </summary>
        public static string your_personal_data_is_protected {
            get {
                return ResourceManager.GetString("your_personal_data_is_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences have been saved.
        /// </summary>
        public static string your_preferences_have_been_saved {
            get {
                return ResourceManager.GetString("your_preferences_have_been_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string zip_code {
            get {
                return ResourceManager.GetString("zip_code", resourceCulture);
            }
        }
    }
}
