//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Resources.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        public static string account_delete_confirmation {
            get {
                return ResourceManager.GetString("account_delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address updated successfully.
        /// </summary>
        public static string address_updated_successfully {
            get {
                return ResourceManager.GetString("address_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string all_rights_reserved {
            get {
                return ResourceManager.GetString("all_rights_reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string already_have_an_account {
            get {
                return ResourceManager.GetString("already_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calulator.
        /// </summary>
        public static string calculator {
            get {
                return ResourceManager.GetString("calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA has errors.
        /// </summary>
        public static string captcha_errors {
            get {
                return ResourceManager.GetString("captcha_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA expired, please do it again.
        /// </summary>
        public static string captcha_expired_please_do_it_again {
            get {
                return ResourceManager.GetString("captcha_expired_please_do_it_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string change_password {
            get {
                return ResourceManager.GetString("change_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string change_your_password {
            get {
                return ResourceManager.GetString("change_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string confirm_email {
            get {
                return ResourceManager.GetString("confirm_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string confirm_new_password {
            get {
                return ResourceManager.GetString("confirm_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact dev team.
        /// </summary>
        public static string contact_dev_team {
            get {
                return ResourceManager.GetString("contact_dev_team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string create_an_account {
            get {
                return ResourceManager.GetString("create_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string current_password {
            get {
                return ResourceManager.GetString("current_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete account.
        /// </summary>
        public static string delete_account {
            get {
                return ResourceManager.GetString("delete_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action is irreversible. All your data will be lost. You will have a 30 day grace period to recover your account.&lt;br/&gt;
        ///        To recover your account, just login with your email and password..
        /// </summary>
        public static string delete_warning {
            get {
                return ResourceManager.GetString("delete_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected a networking issue.
        /// </summary>
        public static string detected_a_networking_issue {
            get {
                return ResourceManager.GetString("detected_a_networking_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Didn&apos;t receive an email?.
        /// </summary>
        public static string didnt_receive_an_email {
            get {
                return ResourceManager.GetString("didnt_receive_an_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string dont_have_an_account {
            get {
                return ResourceManager.GetString("dont_have_an_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent.
        /// </summary>
        public static string email_sent {
            get {
                return ResourceManager.GetString("email_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email, and we&apos;ll send you a link..
        /// </summary>
        public static string enter_your_email_and_well_send_you_a_new_link {
            get {
                return ResourceManager.GetString("enter_your_email_and_well_send_you_a_new_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email to receive notifications about product updates and our newsletter..
        /// </summary>
        public static string enter_your_email_to_receive_notifications_about_product_updates {
            get {
                return ResourceManager.GetString("enter_your_email_to_receive_notifications_about_product_updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate token.
        /// </summary>
        public static string failed_to_validate_token {
            get {
                return ResourceManager.GetString("failed_to_validate_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faq.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgot_password {
            get {
                return ResourceManager.GetString("forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string full_name {
            get {
                return ResourceManager.GetString("full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPTCHA failed to load, please reload the page.
        /// </summary>
        public static string google_recaptcha_error_please_reload {
            get {
                return ResourceManager.GetString("google_recaptcha_error_please_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello world.
        /// </summary>
        public static string hello_world {
            get {
                return ResourceManager.GetString("hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a confirmed account with us, a link with the password reset code will be sent to you..
        /// </summary>
        public static string if_you_have_an_account_with_us_you_should_receive_a_password_reset_code_shortly {
            get {
                return ResourceManager.GetString("if_you_have_an_account_with_us_you_should_receive_a_password_reset_code_shortly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string invalid_token {
            get {
                return ResourceManager.GetString("invalid_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string learn_more {
            get {
                return ResourceManager.GetString("learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string locked_out {
            get {
                return ResourceManager.GetString("locked_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to your account.
        /// </summary>
        public static string login_to_your_account {
            get {
                return ResourceManager.GetString("login_to_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string manage_account {
            get {
                return ResourceManager.GetString("manage_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage notifications.
        /// </summary>
        public static string manage_notifications {
            get {
                return ResourceManager.GetString("manage_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your addresses.
        /// </summary>
        public static string manage_your_addresses {
            get {
                return ResourceManager.GetString("manage_your_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your personal info.
        /// </summary>
        public static string manage_your_personal_info {
            get {
                return ResourceManager.GetString("manage_your_personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Addresses.
        /// </summary>
        public static string my_addresses {
            get {
                return ResourceManager.GetString("my_addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Packages.
        /// </summary>
        public static string my_packages {
            get {
                return ResourceManager.GetString("my_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string new_password {
            get {
                return ResourceManager.GetString("new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string newsletter {
            get {
                return ResourceManager.GetString("newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification preferences.
        /// </summary>
        public static string notification_preferences {
            get {
                return ResourceManager.GetString("notification_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner sites.
        /// </summary>
        public static string partner_sites {
            get {
                return ResourceManager.GetString("partner_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least 12 characters.
        /// </summary>
        public static string password_must_contain_at_least_12_characters {
            get {
                return ResourceManager.GetString("password_must_contain_at_least_12_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully.
        /// </summary>
        public static string password_reset_successfully {
            get {
                return ResourceManager.GetString("password_reset_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID.
        /// </summary>
        public static string personal_id {
            get {
                return ResourceManager.GetString("personal_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string personal_info {
            get {
                return ResourceManager.GetString("personal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email.
        /// </summary>
        public static string please_check_your_email {
            get {
                return ResourceManager.GetString("please_check_your_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and spam folders.
        /// </summary>
        public static string please_check_your_email_and_spam_folder {
            get {
                return ResourceManager.GetString("please_check_your_email_and_spam_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete CAPTCHA before continuing.
        /// </summary>
        public static string please_complete_captcha_before_continuing {
            get {
                return ResourceManager.GetString("please_complete_captcha_before_continuing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Races.
        /// </summary>
        public static string races {
            get {
                return ResourceManager.GetString("races", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive SMS notifications?.
        /// </summary>
        public static string receive_sms_notifications {
            get {
                return ResourceManager.GetString("receive_sms_notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register confirmation.
        /// </summary>
        public static string register_confirmation {
            get {
                return ResourceManager.GetString("register_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string reload {
            get {
                return ResourceManager.GetString("reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string resend {
            get {
                return ResourceManager.GetString("resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string resend_email_confirmation {
            get {
                return ResourceManager.GetString("resend_email_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string reset_password {
            get {
                return ResourceManager.GetString("reset_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room code.
        /// </summary>
        public static string room_code {
            get {
                return ResourceManager.GetString("room_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save preferences.
        /// </summary>
        public static string save_preferences {
            get {
                return ResourceManager.GetString("save_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string show_password {
            get {
                return ResourceManager.GetString("show_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State is unavailable in Georgia.
        /// </summary>
        public static string state_unavailable_for_georgia {
            get {
                return ResourceManager.GetString("state_unavailable_for_georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street address.
        /// </summary>
        public static string street_address {
            get {
                return ResourceManager.GetString("street_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms.
        /// </summary>
        public static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token you provided is invalid.
        /// </summary>
        public static string the_token_you_provided_is_invalid {
            get {
                return ResourceManager.GetString("the_token_you_provided_is_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again in 5 minutes.
        /// </summary>
        public static string this_account_has_been_locked_out_please_try_again_later {
            get {
                return ResourceManager.GetString("this_account_has_been_locked_out_please_try_again_later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a major issue.
        /// </summary>
        public static string this_is_not_a_major_issue {
            get {
                return ResourceManager.GetString("this_is_not_a_major_issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue using the website please reload.
        /// </summary>
        public static string to_continue_please_reload {
            get {
                return ResourceManager.GetString("to_continue_please_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track package.
        /// </summary>
        public static string track_package {
            get {
                return ResourceManager.GetString("track_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;delete&apos; to confirm.
        /// </summary>
        public static string type_delete_to_confirm {
            get {
                return ResourceManager.GetString("type_delete_to_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update address.
        /// </summary>
        public static string update_address {
            get {
                return ResourceManager.GetString("update_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back.
        /// </summary>
        public static string welcome_back {
            get {
                return ResourceManager.GetString("welcome_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the best app ever!.
        /// </summary>
        public static string welcome_to_our_app {
            get {
                return ResourceManager.GetString("welcome_to_our_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource.
        /// </summary>
        public static string you_do_not_have_access_to_this_resource {
            get {
                return ResourceManager.GetString("you_do_not_have_access_to_this_resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a 30 day grace period to recover your account. To recover your account, login with your email and password..
        /// </summary>
        public static string you_have_a_30_day_grace_period_to_recover_your_account_to_recover_simply_login {
            get {
                return ResourceManager.GetString("you_have_a_30_day_grace_period_to_recover_your_account_to_recover_simply_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree to our.
        /// </summary>
        public static string you_must_agree_to_our {
            get {
                return ResourceManager.GetString("you_must_agree_to_our", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully reset your password.
        /// </summary>
        public static string you_successfully_reset_your_password {
            get {
                return ResourceManager.GetString("you_successfully_reset_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been confirmed.
        /// </summary>
        public static string your_account_has_been_confirmed {
            get {
                return ResourceManager.GetString("your_account_has_been_confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is scheduled for deletion.
        /// </summary>
        public static string your_account_is_scheduled_for_deletion {
            get {
                return ResourceManager.GetString("your_account_is_scheduled_for_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.
        /// </summary>
        public static string your_password_has_been_reset {
            get {
                return ResourceManager.GetString("your_password_has_been_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal data is protected.
        /// </summary>
        public static string your_personal_data_is_protected {
            get {
                return ResourceManager.GetString("your_personal_data_is_protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences have been saved.
        /// </summary>
        public static string your_preferences_have_been_saved {
            get {
                return ResourceManager.GetString("your_preferences_have_been_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code.
        /// </summary>
        public static string zip_code {
            get {
                return ResourceManager.GetString("zip_code", resourceCulture);
            }
        }
    }
}
